# ==============================================================================
# Generated by qmake (2.01a) (Qt 4.7.0) on: Tue 17. Aug 12:44:27 2010
# This file is generated by qmake and should not be modified by the
# user.
#  Name        : z:/qtwebkit-symbian-qtp/Makefile
#  Description : Wrapper Makefile for calling Symbian build tools
#
# ==============================================================================


MAKEFILE          = Makefile
QMAKE             = \epoc32\tools\qmake.exe
DEL_FILE          = del 2> NUL
DEL_DIR           = rmdir
CHK_DIR_EXISTS    = if not exist
MKDIR             = mkdir
MOVE              = move
DEBUG_PLATFORMS   = winscw gcce armv5 armv6
RELEASE_PLATFORMS = gcce armv5 armv6
MAKE              = make
SBS               = sbs

DEFINES	 = -DSYMBIAN -DUNICODE -DQT_KEYPAD_NAVIGATION -DQT_SOFTKEYS_ENABLED -DQT_USE_MATH_H_FLOATS -DBUILDING_QT__=1 -DWTF_USE_ACCELERATED_COMPOSITING -DUSE_SYSTEM_MALLOC -DQT_NO_UITOOLS -DBUILDING_QT__=1 -DWTF_USE_ACCELERATED_COMPOSITING -DUSE_SYSTEM_MALLOC -DQT_GUI_LIB -DQT_CORE_LIB
INCPATH	 =  -I"Z:/epoc32/include/mw/QtCore"  -I"Z:/epoc32/include/mw/QtGui"  -I"Z:/epoc32/include/mw"  -I"Z:/sf/mw/qt/mkspecs/common/symbian"  -I"Z:/epoc32/include"  -I"Z:/epoc32/include/stdapis"  -I"Z:/epoc32/include/stdapis/sys"  -I"Z:/epoc32/include/platform/mw"  -I"Z:/epoc32/include/platform"  -I"Z:/epoc32/include/platform/loc"  -I"Z:/epoc32/include/platform/mw/loc"  -I"Z:/epoc32/include/platform/loc/sc"  -I"Z:/epoc32/include/platform/mw/loc/sc"  -I"Z:/qtwebkit-symbian-qtp/include/QtWebKit"  -I"Z:/epoc32/include/stdapis/stlportv5"  -I"Z:/qtwebkit-symbian-qtp" 
first: default
default: debug-winscw
all: debug release

qmake:
	$(QMAKE) -spec symbian-sbsv2 -o "bld.inf" "Z:/qtwebkit-symbian-qtp/WebKit.pro"

bld.inf:
	$(QMAKE)

debug: bld.inf
	$(SBS) -c winscw_udeb.mwccinc -c gcce_udeb -c armv5_udeb -c armv6_udeb
release: bld.inf
	$(SBS) -c gcce_urel -c armv5_urel -c armv6_urel
debug-winscw: bld.inf
	$(SBS) -c winscw_udeb.mwccinc
debug-gcce: bld.inf
	$(SBS) -c gcce_udeb
debug-armv5: bld.inf
	$(SBS) -c armv5_udeb
debug-armv6: bld.inf
	$(SBS) -c armv6_udeb
release-gcce: bld.inf
	$(SBS) -c gcce_urel
release-armv5: bld.inf
	$(SBS) -c armv5_urel
release-armv6: bld.inf
	$(SBS) -c armv6_urel

export: bld.inf
	$(SBS) export

cleanexport: bld.inf
	$(SBS) cleanexport

JavaScriptCore\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) JavaScriptCore\ $(MKDIR) JavaScriptCore\ 
	cd JavaScriptCore\ && $(QMAKE) z:\qtwebkit-symbian-qtp\JavaScriptCore\JavaScriptCore.pro -o $(MAKEFILE)
sub-JavaScriptCore-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) JavaScriptCore\ $(MKDIR) JavaScriptCore\ 
	cd JavaScriptCore\ && $(QMAKE) z:\qtwebkit-symbian-qtp\JavaScriptCore\JavaScriptCore.pro -o $(MAKEFILE)
sub-JavaScriptCore: JavaScriptCore\$(MAKEFILE) FORCE
	cd JavaScriptCore\ && $(MAKE) -f $(MAKEFILE)
WebCore\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) WebCore\ $(MKDIR) WebCore\ 
	cd WebCore\ && $(QMAKE) z:\qtwebkit-symbian-qtp\WebCore\WebCore.pro -o $(MAKEFILE)
sub-WebCore-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) WebCore\ $(MKDIR) WebCore\ 
	cd WebCore\ && $(QMAKE) z:\qtwebkit-symbian-qtp\WebCore\WebCore.pro -o $(MAKEFILE)
sub-WebCore: WebCore\$(MAKEFILE) FORCE
	cd WebCore\ && $(MAKE) -f $(MAKEFILE)
WebKit\qt\declarative\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) WebKit\qt\declarative\ $(MKDIR) WebKit\qt\declarative\ 
	cd WebKit\qt\declarative\ && $(QMAKE) z:\qtwebkit-symbian-qtp\WebKit\qt\declarative\declarative.pro -o $(MAKEFILE)
sub-WebKit-qt-declarative-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) WebKit\qt\declarative\ $(MKDIR) WebKit\qt\declarative\ 
	cd WebKit\qt\declarative\ && $(QMAKE) z:\qtwebkit-symbian-qtp\WebKit\qt\declarative\declarative.pro -o $(MAKEFILE)
sub-WebKit-qt-declarative: WebKit\qt\declarative\$(MAKEFILE) FORCE
	cd WebKit\qt\declarative\ && $(MAKE) -f $(MAKEFILE)
JavaScriptCore\$(MAKEFILE).jsc: 
	@$(CHK_DIR_EXISTS) JavaScriptCore\ $(MKDIR) JavaScriptCore\ 
	cd JavaScriptCore\ && $(QMAKE) z:\qtwebkit-symbian-qtp\JavaScriptCore\jsc.pro -o $(MAKEFILE).jsc
sub-JavaScriptCore-jsc-pro-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) JavaScriptCore\ $(MKDIR) JavaScriptCore\ 
	cd JavaScriptCore\ && $(QMAKE) z:\qtwebkit-symbian-qtp\JavaScriptCore\jsc.pro -o $(MAKEFILE).jsc
sub-JavaScriptCore-jsc-pro: JavaScriptCore\$(MAKEFILE).jsc FORCE
	cd JavaScriptCore\ && $(MAKE) -f $(MAKEFILE).jsc


install:
	$(MAKE) -C WebCore install

docs:
	SRCDIR=Z:/qtwebkit-symbian-qtp/WebKit/qt/docs/../../.. OUTPUT_DIR= /bin/qdoc3 Z:/qtwebkit-symbian-qtp/WebKit/qt/docs/qtwebkit.qdocconf

sub-JavaScriptCore-check: JavaScriptCore\$(MAKEFILE)
	cd JavaScriptCore\ && $(MAKE) check
sub-WebCore-check: WebCore\$(MAKEFILE)
	cd WebCore\ && $(MAKE) check
sub-WebKit-qt-declarative-check: WebKit\qt\declarative\$(MAKEFILE)
	cd WebKit\qt\declarative\ && $(MAKE) check
sub-JavaScriptCore-jsc-pro-check: JavaScriptCore\$(MAKEFILE).jsc
	cd JavaScriptCore\ && $(MAKE) -f $(MAKEFILE).jsc check
check: sub-JavaScriptCore-check sub-WebCore-check sub-WebKit-qt-declarative-check sub-JavaScriptCore-jsc-pro-check

sub-JavaScriptCore-sis_target: JavaScriptCore\$(MAKEFILE)
	cd JavaScriptCore\ && $(MAKE) sis
sub-WebCore-sis_target: WebCore\$(MAKEFILE)
	cd WebCore\ && $(MAKE) sis
sub-WebKit-qt-declarative-sis_target: WebKit\qt\declarative\$(MAKEFILE)
	cd WebKit\qt\declarative\ && $(MAKE) sis
sub-JavaScriptCore-jsc-pro-sis_target: JavaScriptCore\$(MAKEFILE).jsc
	cd JavaScriptCore\ && $(MAKE) -f $(MAKEFILE).jsc sis
sis: sub-JavaScriptCore-sis_target sub-WebCore-sis_target sub-WebKit-qt-declarative-sis_target sub-JavaScriptCore-jsc-pro-sis_target

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
FORCE:

dodistclean:
	-$(MAKE) -f "z:\qtwebkit-symbian-qtp\JavaScriptCore\Makefile" dodistclean
	-$(MAKE) -f "z:\qtwebkit-symbian-qtp\WebCore\Makefile" dodistclean
	-$(MAKE) -f "z:\qtwebkit-symbian-qtp\WebKit\qt\declarative\Makefile" dodistclean
	-$(MAKE) -f "z:\qtwebkit-symbian-qtp\JavaScriptCore\Makefile.jsc" dodistclean
	-@ if EXIST "z:\qtwebkit-symbian-qtp\Makefile" $(DEL_FILE)  "z:\qtwebkit-symbian-qtp\Makefile"
	-@ if EXIST "z:\qtwebkit-symbian-qtp\bld.inf" $(DEL_FILE)  "z:\qtwebkit-symbian-qtp\bld.inf"

distclean: clean dodistclean

clean: bld.inf
	-$(SBS) reallyclean

clean-debug: bld.inf
	$(SBS) reallyclean -c winscw_udeb -c gcce_udeb -c armv5_udeb -c armv6_udeb
clean-release: bld.inf
	$(SBS) reallyclean -c gcce_urel -c armv5_urel -c armv6_urel
clean-debug-winscw: bld.inf
	$(SBS) reallyclean -c winscw_udeb
clean-debug-gcce: bld.inf
	$(SBS) reallyclean -c gcce_udeb
clean-debug-armv5: bld.inf
	$(SBS) reallyclean -c armv5_udeb
clean-debug-armv6: bld.inf
	$(SBS) reallyclean -c armv6_udeb
clean-release-gcce: bld.inf
	$(SBS) reallyclean -c gcce_urel
clean-release-armv5: bld.inf
	$(SBS) reallyclean -c armv5_urel
clean-release-armv6: bld.inf
	$(SBS) reallyclean -c armv6_urel

